
const data = 
[
  {
    "id": 1,
    "firstname": "Wilhelm Conrad",
    "surname": "Röntgen",
    "born": "1845-03-27",
    "died": "1923-02-10",
    "bornCountry": "Prussia (now Germany)",
    "bornCity": "Lennep (now Remscheid)",
    "diedCountry": "Germany",
    "diedCity": "Munich",
    "gender": "male",
    "year": 1901,
    "category": "physics",
    "share": 1,
    "name": "Munich University",
    "city": "Munich",
    "stuff": ["red", "blue", "green"],
    "country": "Germany"
  },
  {
    "id": 2,
    "firstname": "Hendrik Antoon",
    "surname": "Lorentz",
    "born": "1853-07-18",
    "died": "1928-02-04",
    "bornCountry": "the Netherlands",
    "bornCity": "Arnhem",
    "diedCountry": "the Netherlands",
    "diedCity": "",
    "gender": "male",
    "year": 1902,
    "category": "physics",
    "share": 2,
    "name": "Leiden University",
    "stuff": ["red"],
    "city": "Leiden",
    "country": "the Netherlands"
  },
  {
    "id": 3,
    "firstname": "Pieter",
    "surname": "Zeeman",
    "born": "1865-05-25",
    "died": "1943-10-09",
    "bornCountry": "the Netherlands",
    "bornCity": "Zonnemaire",
    "diedCountry": "the Netherlands",
    "diedCity": "Amsterdam",
    "gender": "male",
    "year": 1902,
    "category": "physics",
    "share": 2,
    "name": "Amsterdam University",
    "stuff": ["red", "blue", "green"],
    "city": "Amsterdam",
    "country": "the Netherlands"
  },
  {
    "id": 4,
    "firstname": "Antoine Henri",
    "surname": "Becquerel",
    "born": "1852-12-15",
    "died": "1908-08-25",
    "bornCountry": "France",
    "bornCity": "Paris",
    "diedCountry": "France",
    "diedCity": "",
    "gender": "male",
    "year": 1903,
    "category": "physics",
    "share": 2,
    "name": "École Polytechnique",
    "stuff": ["green"],
    "city": "Paris",
    "country": "France"
  }
];

export default data;
