export const ranges__row: string;
export const rangesRow: string;
export const ranges__item: string;
export const rangesItem: string;
export const ranges__column: string;
export const rangesColumn: string;
export const ranges__value: string;
export const rangesValue: string;
export const rangesFilteredColumn: string;
